language: d
script: 
  - dub build
  - mv redo---redoing redo
  - ln redo redo-ifchange
  - export PATH=.:$PATH
  - redo test
install:
  # leveldb
  # dmd
  # dub
  - sudo apt-get install libsnappy-dev
  - git clone https://code.google.com/p/leveldb
  - cd leveldb
  - make
  - sudo cp --preserve=links libleveldb.* /usr/local/lib
  - sudo cp -r include/leveldb /usr/local/include/
  - sudo ldconfig
  - cd ..
  - DMD_VER=2.065.0
  - DMD=dmd_${DMD_VER}-0_amd64.deb
  - DUB_VER=0.9.21
  - DUB=dub-${DUB_VER}-linux-x86_64
  - wget http://downloads.dlang.org/releases/2014/${DMD}
  - sudo dpkg -i ${DMD} || true
  - sudo apt-get -y update
  - sudo apt-get -fy install
  - sudo dpkg -i ${DMD}
  - wget http://code.dlang.org/files/${DUB}.tar.gz
  - sudo tar -C /usr/local/bin -zxf ${DUB}.tar.gz
